# Generated by Django 4.2.30 on 2026-05-15 23:35

from django.db import migrations, models
import django.db.models.deletion


def populate_legacy_variant_options(apps, schema_editor):
    ProductOption = apps.get_model('shop', 'ProductOption')
    ProductOptionValue = apps.get_model('shop', 'ProductOptionValue')
    ProductVariant = apps.get_model('shop', 'ProductVariant')
    ProductVariantSelectedOption = apps.get_model('shop', 'ProductVariantSelectedOption')

    legacy_option_fields = (
        ('color', 'Color', 1),
        ('size', 'Size', 2),
        ('finish', 'Finish', 3),
    )

    for variant in ProductVariant.objects.all():
        for field_name, option_name, sort_order in legacy_option_fields:
            raw_value = getattr(variant, field_name, '') or ''
            option_value_text = raw_value.strip()
            if not option_value_text:
                continue

            option, _created = ProductOption.objects.get_or_create(
                product_id=variant.product_id,
                name=option_name,
                defaults={'sort_order': sort_order},
            )
            option_value, _created = ProductOptionValue.objects.get_or_create(
                option_id=option.id,
                value=option_value_text,
                defaults={'sort_order': sort_order},
            )
            selection, created = ProductVariantSelectedOption.objects.get_or_create(
                variant_id=variant.id,
                option_id=option.id,
                defaults={'option_value_id': option_value.id, 'sort_order': sort_order},
            )
            if not created and selection.option_value_id != option_value.id:
                selection.option_value_id = option_value.id
                selection.sort_order = sort_order
                selection.save(update_fields=['option_value', 'sort_order', 'updated_at'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_values', to='shop.productoption')),
            ],
            options={
                'ordering': ['option__sort_order', 'sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product__name', 'sku']},
        ),
        migrations.CreateModel(
            name='ProductVariantSelectedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_selections', to='shop.productoption')),
                ('option_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_selections', to='shop.productoptionvalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='shop.productvariant')),
            ],
            options={
                'ordering': ['sort_order', 'option__sort_order', 'id'],
            },
        ),
        migrations.RunPython(populate_legacy_variant_options, noop_reverse),
        migrations.AddConstraint(
            model_name='productvariantselectedoption',
            constraint=models.UniqueConstraint(fields=('variant', 'option'), name='unique_variant_option_selection'),
        ),
        migrations.AddConstraint(
            model_name='productoptionvalue',
            constraint=models.UniqueConstraint(fields=('option', 'value'), name='unique_option_value'),
        ),
        migrations.AddConstraint(
            model_name='productoption',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_product_option_name'),
        ),
    ]
