# Generated by Django 4.2.30 on 2026-05-16 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('pickup_instructions', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_pickup_enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VariantInventoryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='shop.storelocation')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='shop.productvariant')),
            ],
            options={
                'ordering': ['location__sort_order', 'location__name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='pickup_locations',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.storelocation'),
        ),
        migrations.AddConstraint(
            model_name='variantinventorylevel',
            constraint=models.UniqueConstraint(fields=('variant', 'location'), name='unique_variant_inventory_location'),
        ),
    ]
